services:
  postgres:
    image: postgres:16-alpine
    container_name: miniloja-postgres
    environment:
      POSTGRES_DB: miniloja
      POSTGRES_USER: miniloja
      POSTGRES_PASSWORD: miniloja
    ports:
      - "5432:5432"
    volumes:
      - miniloja_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miniloja -d miniloja"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: miniloja-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - miniloja_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  miniloja_pgdata:
  miniloja_redisdata:
