spring.application.name=miniloja
spring.profiles.active=dev

# Postgres (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/miniloja
spring.datasource.username=miniloja
spring.datasource.password=miniloja
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis (dev) - reservado para uso futuro (cache/session/etc.)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

info.app.name=MiniLoja
info.app.description=Sistema de controle de produtos, vendas e caixa
info.app.version=0.0.1-SNAPSHOT
